import {
  Home,
  MessageSquare,
  FolderKanban,
  Lightbulb,
  Building2,
  Users,
  LogOut,
  Shield,
  Link2,
  UserCog,
  FileText,
  BarChartHorizontal,
  Trash2,
  Zap,
  Target,
  Settings,
  Sparkles,
  Briefcase,
  DollarSign,
  BarChart2,
  Building,
  Clock,
  GitBranch,
  Brain,
} from "lucide-react";
import { useLocation, Link } from "wouter";
import { useQuery } from "@tanstack/react-query";
import { useState, useEffect } from "react";

interface BrandingSettings {
  agencyLogo: string | null;
  clientLogo: string | null;
  staffLogo: string | null;
}
import {
  Sidebar,
  SidebarContent,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarHeader,
  SidebarSeparator,
  useSidebar,
} from "@/components/ui/sidebar";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { Badge } from "@/components/ui/badge";
import { getAuthUser, clearAuthUser } from "@/lib/auth";

const menuGroups = [
  {
    title: "Core",
    icon: Zap,
    items: [
      {
        title: "Agency View",
        url: "/agency",
        icon: Home,
        notificationKey: null,
        description: "Your dashboard with key metrics and quick actions",
      },
      {
        title: "Client Messages",
        url: "/agency/messages",
        icon: MessageSquare,
        notificationKey: "unreadMessages" as const,
        description: "View and respond to client support conversations",
      },
      {
        title: "Tasks & Projects",
        url: "/agency/tasks",
        icon: FolderKanban,
        notificationKey: null,
        description: "Manage projects, task lists, and team assignments",
      },
      {
        title: "Hours Report",
        url: "/agency/hours",
        icon: Clock,
        notificationKey: null,
        description: "Track time spent across projects and staff members",
      },
    ],
  },
  {
    title: "Strategy",
    icon: Target,
    items: [
      {
        title: "AI Recommendations",
        url: "/agency/recommendations",
        icon: Lightbulb,
        notificationKey: "unviewedResponses" as const,
        description: "View strategic insights generated by our AI engine",
      },
      {
        title: "Workflows",
        url: "/agency/workflows",
        icon: GitBranch,
        notificationKey: null,
        description: "Build and manage automated workflows",
      },
      {
        title: "Intelligence",
        url: "/agency/intelligence",
        icon: Brain,
        notificationKey: null,
        description: "Operational intelligence signals, insights, and priorities",
      },
    ],
  },
  {
    title: "Administration",
    icon: Shield,
    items: [
      {
        title: "Clients",
        url: "/agency/clients",
        icon: Building2,
        notificationKey: null,
        description: "Manage client accounts, integrations, and access",
      },
      {
        title: "Settings",
        url: "/agency/settings",
        icon: Settings,
        notificationKey: null,
        description: "Configure agency preferences and branding options",
      },
    ],
  },
];

// This function adds Super Admin menu item conditionally
function getMenuItems(isSuperAdmin: boolean) {
  if (!isSuperAdmin) {
    return menuGroups;
  }
  
  // Add Super Admin menu item to Administration group
  const adminGroup = menuGroups.find(g => g.title === "Administration");
  if (adminGroup) {
    return menuGroups.map(group => {
      if (group.title === "Administration") {
        return {
          ...group,
          items: [
            ...group.items,
            {
              title: "Super Admin",
              url: "/superadmin",
              icon: Shield,
              notificationKey: null,
              description: "Platform-wide management and cross-agency access",
            },
          ],
        };
      }
      return group;
    });
  }
  
  return menuGroups;
}

type SidebarMode = 'expanded' | 'collapsed' | 'hover';

export function AgencySidebar() {
  const [location, setLocation] = useLocation();
  const authUser = getAuthUser();
  const { setOpen, open, setOpenMobile, isMobile } = useSidebar();
  
  const [sidebarMode, setSidebarMode] = useState<SidebarMode>(
    () => (localStorage.getItem('sidebarMode') as SidebarMode) || 'expanded'
  );

  const { data: notificationCounts } = useQuery<{ unreadMessages: number; unviewedResponses: number }>({
    queryKey: ["/api/agency/notifications/counts"],
    refetchInterval: 10000,
  });

  const { data: branding } = useQuery<BrandingSettings>({
    queryKey: ['/api/agency/settings/branding'],
    staleTime: 5 * 60 * 1000,
  });

  // Listen for sidebar mode changes from Settings
  useEffect(() => {
    const handleSidebarModeChange = (event: CustomEvent<SidebarMode>) => {
      setSidebarMode(event.detail);
      if (event.detail === 'collapsed') {
        setOpen(false);
      } else if (event.detail === 'expanded') {
        setOpen(true);
      }
    };

    window.addEventListener('sidebarModeChange', handleSidebarModeChange as EventListener);
    return () => {
      window.removeEventListener('sidebarModeChange', handleSidebarModeChange as EventListener);
    };
  }, [setOpen]);

  // Set initial state based on mode
  useEffect(() => {
    if (sidebarMode === 'collapsed') {
      setOpen(false);
    } else if (sidebarMode === 'expanded') {
      setOpen(true);
    }
  }, [sidebarMode, setOpen]);

  const handleLogout = () => {
    clearAuthUser();
    setLocation("/login");
  };

  const handleNavClick = () => {
    if (isMobile) {
      setOpenMobile(false);
    }
  };
  
  // Check if user is Super Admin
  const isSuperAdmin = authUser?.profile?.isSuperAdmin || false;

  return (
    <Sidebar 
      collapsible={sidebarMode === 'hover' || sidebarMode === 'collapsed' ? 'icon' : 'offcanvas'}
      onMouseEnter={() => sidebarMode === 'hover' && setOpen(true)}
      onMouseLeave={() => sidebarMode === 'hover' && setOpen(false)}
    >
      <SidebarHeader className="p-4">
        <div className="flex flex-col gap-3">
          {branding?.agencyLogo ? (
            <div className="h-10 w-auto max-w-[120px] flex items-center group-data-[collapsible=icon]:h-8 group-data-[collapsible=icon]:max-w-[32px] group-data-[collapsible=icon]:justify-center">
              <img 
                src={branding.agencyLogo} 
                alt="Agency Logo" 
                className="h-full w-auto object-contain"
                data-testid="img-agency-logo"
              />
            </div>
          ) : (
            <div className="h-10 w-10 rounded-lg bg-primary/10 flex items-center justify-center group-data-[collapsible=icon]:h-8 group-data-[collapsible=icon]:w-8">
              <Shield className="h-5 w-5 text-primary group-data-[collapsible=icon]:h-4 group-data-[collapsible=icon]:w-4" />
            </div>
          )}
          <div className="flex flex-col group-data-[collapsible=icon]:hidden">
            <span className="font-semibold text-sm">Team manager</span>
            <span className="text-xs text-muted-foreground">{authUser?.profile.fullName}</span>
          </div>
        </div>
      </SidebarHeader>
      <SidebarContent className="p-2">
        {getMenuItems(isSuperAdmin).map((group, index) => (
          <div key={group.title}>
            {index > 0 && <SidebarSeparator className="my-3 bg-border" />}
            <SidebarMenu>
              {group.items.map((item) => {
                const count = item.notificationKey && notificationCounts
                  ? notificationCounts[item.notificationKey]
                  : 0;

                return (
                  <SidebarMenuItem key={item.title}>
                    <Tooltip delayDuration={300}>
                      <TooltipTrigger asChild>
                        <SidebarMenuButton
                          asChild
                          isActive={location === item.url}
                          tooltip={!open ? item.title : undefined}
                          data-testid={`nav-${item.title.toLowerCase().replace(/\s+/g, '-')}`}
                        >
                          <Link href={item.url} onClick={handleNavClick}>
                            <item.icon className="h-4 w-4" />
                            <span className="flex-1">{item.title}</span>
                            {count > 0 && (
                              <Badge
                                variant="default"
                                className="ml-auto h-5 min-w-5 px-1 text-xs"
                                data-testid={`notification-badge-${item.notificationKey}`}
                              >
                                {count}
                              </Badge>
                            )}
                          </Link>
                        </SidebarMenuButton>
                      </TooltipTrigger>
                      {open && item.description && (
                        <TooltipContent 
                          side="right" 
                          align="center"
                          className="max-w-[200px] text-xs"
                        >
                          {item.description}
                        </TooltipContent>
                      )}
                    </Tooltip>
                  </SidebarMenuItem>
                );
              })}
            </SidebarMenu>
          </div>
        ))}
      </SidebarContent>
      <div className="p-2 mt-auto border-t">
        <SidebarMenu>
          <SidebarMenuItem>
            <SidebarMenuButton onClick={handleLogout} tooltip="Logout" data-testid="nav-logout">
              <LogOut className="h-4 w-4" />
              <span>Logout</span>
            </SidebarMenuButton>
          </SidebarMenuItem>
        </SidebarMenu>
      </div>
    </Sidebar>
  );
}
